### ISSUE TITLE
Not receiving iAds in simulator...

### ISSUE THREAD

**Issue by geogerar** [vladislav-k/VKAdBannerView#1]
Hi,
Thank you for your nice tool but I have a question.
I tried to run your example in simulator but I don't receiving any iAd.
Why?
Can you take look and answer me?

Thanks again

George Gerardis

**Comment by vladislav-k** [comment]
Hi @geogerar,

as I know, iAd is deprecated by Apple since June 2016, so I think that's the reason why you don't see it. Example project was created before this date, that's why I didn't update third party Ad. But you can follow the way I used it with iAd and replace Apple's Ad service with any another one.

Thanks
